name: MultiModalPretrainedViTLab
output_logits: 1
num_channels: 3
type: 'vit_small_patch16_384'
transforms:
  img_size: 384
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
meta:
  patch_size: 16
  dim: 384 # Has to be set according to the pretrained model
  depth: 4
  heads: 4
  mlp_dim: 768
  pool: 'cls'
  dim_head: 128
  dropout: 0.
  emb_dropout: 0.
  p_visual_dropout: 0.
  p_feature_dropout: 0.

